version: '3'
services:
  backend:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "7000:8000"
    depends_on:
      - db
  db:
    image: 'postgres:14'
    environment:
      POSTGRES_DB: 'afisha_db'
      POSTGRES_USER: 'afisha_user'
      POSTGRES_PASSWORD: '1234'
    volumes:
      - 'new-data:/var/lib/postgresql/data'
volumes:
  new-data:
